### PR TITLE
284 add support for camtrap dp v1.0

### PR DESCRIPTION
**Pull request by PietrH**
# STATUS: Ready for review
- [x] Check that all mentions of the release candidate are removed and replaced by `v1.0`

### test-read_camptrap_dp.R

- [x] `deployments.baitUse` is expected to be `NA` but is actually `none`, it should be NA since it's `false` in the source,  these values **have** changed between the examples in the `rc` and` v1.0`
- [x] `deployments.session` is expected to be `NA` but has values from `deploymentGroups`, these values **have** changed between the examples in the `rc` and` v1.0`

## Missing tests

I feel additional coverage was needed for the changes below, since we were passing tests for a new v1.0 camtrap-dp even though they were not implemented yet.

Add tests for:

- [x] Downconversion of `media.captureMethod` values `activityDetection` to `motionDetection`
- [x] Downconversion of `project.catureMethod` (in metadata) values `activityDetection` to `motionDetection`

### CODE REVIEW

**Comment by PietrH** [comment]
I seem to have pulled some code from #282 into `test-read_camtrap_dp.R` by accident, I'll try to remove anything that might result in merge conflicts with #282

**Comment by PietrH** [comment]
> - [ ] `deployments.baitUse` is expected to be `NA` but is actually `none`, it should be NA since it's `false` in the source

Seems to me this is pretty intentional:

https://github.com/inbo/camtraptor/blob/db6c53ab563c095064ee10a8728447f1b4aa8e42/R/zzz.R#L578

**Comment by peterdesmet** [comment]
Are you using the Camtrap DP 1.0 example package? `baitUse: false` should indeed be translated to `none` (in 0.1.6)

**Comment by PietrH** [comment]
I am using the v1.0 example package, referring directly: https://raw.githubusercontent.com/tdwg/camtrap-dp/1.0/example/datapackage.json

My current hypothesis is a difference between the RC and v1.0 example packages causing the test to fail.

**Comment by peterdesmet** [comment]
Yes, the example package has been populated with more data between 1.0-RC.1 and 1.0

**Comment by PietrH** [comment]
The most conservative solution would be to include some of the NA values in the package that is used to test camtraptor. I prefer this over removing the test.

**Comment by peterdesmet** [comment]
I would just use the package as is and remove some of the tests. They are only used to test the downconversion, which will disappear at some point.

**Comment by PietrH** [comment]
> I would just use the package as is and remove some of the tests. They are only used to test the downconversion, which will disappear at some point.

I'd rather skip the test for now, so it's easier to debug if it does happen to break before we switch to the different data model in camtraptor. Skipping implemented in fb477ef7b5a57cba326da1f331edcebb44e164b5

**Comment by PietrH** [comment]
@peterdesmet Should `deployments.deploymentGroups` be mapped to `deployments.session` in v0.1.6 ?

This is how it works at the moment; 

```R

  if ("deploymentGroups" %in% names(deployments)) {
    # map to session and then remove
    deployments <- deployments %>%
      dplyr::mutate(session = dplyr::case_when(
        is.na(.data$session) ~.data$deploymentGroups,
        is.na(.data$deploymentGroups) ~ .data$session,
        !is.na(.data$deploymentGroups) & !is.na(.data$session) ~ 
          stringr::str_c(.data$session, 
                         .data$deploymentGroups, 
                         sep = " | "))) %>%
      dplyr::select(-"deploymentGroups")
  }
  
  ```
  
  If there is no value for `session`, it becomes `deploymentGroups`, if there is no value for `deploymentGroups`, it become session, if there is a value for both, they are concatenated with a pipe.

**Comment by peterdesmet** [comment]
Regarding `deploymentGroups`: functionality is good, but would simplify and reverse order (so that deploymentGroup info is always kept):

1. Both present: concatenate with pipe
2. deploymentGroups present (and not session): populate session
3. session present: keep in session

Remove deploymentGroups afterwards

**Comment by PietrH** [comment]
Ready for review, something is going wrong building the vignettes, any idea's?

**Review by peterdesmet — APPROVED** [review]

**Comment by damianooldoni** [comment]
I couldn't reproduce the error while building the vignette with `windows-latest`+ R 3.6.0. 
It's a problem while generating the ["black multiply"](https://img.icons8.com/ios-glyphs/30/000000/multiply.png) icon in leaflet. 
I am afraid that leaflet is not really concerned about supporting older R versions on all type of machines. See https://github.com/rstudio/leaflet/actions/runs/6776222357

They support R 3.6.3 on Ubuntu only. Everything runs on Ubuntu except a machine running R 4.3.2 on windows-latest.
My proposal is to remove such check as well and so leaving only the check with Ubuntu + R 3.6.3.

**Comment by PietrH** [comment]
Ok for me

**Comment by peterdesmet** [comment]
Fine by me. Can we merge this request? Note that it contains a version bump to v0.21.0 which you may want to include only after you fixed other issues.

**Comment by damianooldoni** [comment]
To avoid too much confusion with versioning, I think we should just merge this branch to `main` as version 0.21.0 asap. 
I would then leave the version number as it is for the next imminent PRs and then a release will follow.

**Pull request merged**
