### PR TITLE
Extra updates to read_wi()

### PR DESCRIPTION
**Pull request by peterdesmet**
I read the `Data-Dictionary-for-Data-Download.pdf` and updated the mapping of some fields. It also negates the need for a `capture_method` param.

### CODE REVIEW

**Review by damianooldoni — APPROVED** [review]
Thanks to add tests to read_wi() as well. It seems ok to me.

**Comment by damianooldoni** [comment]
@peterdesmet: I have merged PR #155 to `main`. So, before merging this PR, please update from `main`, thanks.

**Comment by Rafnuss** [comment]
I've tested the new code with my dataset and `write_dwc` worked well.
I get the following error for `map_dep()` which I don't understand. 
```
> map_dep(dp, feature = "effort")
Error in stop(assertError(attr(res, "msg"))) : bad error message
Called from: assertthat::assert_that(null_allowed == TRUE, msg = msg_to_print)
```

Otherwise, with `write_eml()`, `title` does not exist in package. Can we create it in `read_wi()`, or is it ok to request it only when writing eml?

Finally, there is a `path` missing in `package$contributors`
```
> write_eml(dp, title = "test")
Please review generated metadata carefully before publishing.
Error in `dplyr::mutate()`:
! Problem while computing `orcid = stringr::str_extract(.data$path, orcid_regex)`.
Caused by error in `.data$path`:
! Column `path` not found in `.data`.
Run `rlang::last_error()` to see where the error occurred.
Called from: signal_abort(cnd, .file)
```

**Comment by peterdesmet** [comment]
@Rafnuss thanks for the feedback. I have split your comment into several issues (since they are about other functions) and will answer there.

**Pull request merged**
