### PR TITLE
Fix 113

### LINKED ISSUE #113: Move the metadata in datapackage up to root level
Currently, the object returned by:

```R
dp <- read_camtrap_dp("inst/extdata/mica/datapackage.json")
```

Is a list with 4 elements:

- dp$observations
- dp$deployments
- dp$media
- dp$datapackage

By nesting all the metadata to a lower level, the resulting `dp` is different from what would be returned by `frictionles::read_package()`. I would make the objects compatible, by moving the metadata up to the root level. We just have to make sure that the added elements (observations, deployments, media) don't conflict with current names (they don't) or by grouping the data in a `data` object (also no name conflict).

I other words:

```
 $ name         : chr "mica-muskrat-and-coypu-20210707160815"
 $ id           : chr "https://doi.org/10.5281/zenodo.4893244"
 $ profile      : chr "https://raw.githubusercontent.com/tdwg/camtrap-dp/0.1.6/camtrap-dp-profile.json"
 $ created      : chr "2021-07-07T16:08:15Z"
 $ sources      :List of 1
 ...
 $ deployments
 $ media
 $ observations
```

Or grouped:

```
 $ name         : chr "mica-muskrat-and-coypu-20210707160815"
 $ id           : chr "https://doi.org/10.5281/zenodo.4893244"
 $ profile      : chr "https://raw.githubusercontent.com/tdwg/camtrap-dp/0.1.6/camtrap-dp-profile.json"
 $ created      : chr "2021-07-07T16:08:15Z"
 $ sources      :List of 1
 ...
 $ data
 ..$ deployments
 ..$ media
 ..$ observations
```

### PR DESCRIPTION
**Pull request by damianooldoni**
This PR aims to fix #113.
To do:

- [x] update functions
- [x] update function documentation
- [x] update tests
- [x] update vignette

In the meantime, #72 has been applied to help functions in `zzz.R` and tests.

Once everything is done, convert to PR.

### CODE REVIEW

**Comment by peterdesmet** [comment]
To stick with the frictionless convention, it might be better to rename the variable `datapkg` -> `package`

**Comment by damianooldoni** [comment]
Yes, @peterdesmet, that's issue #112. I thought to do it separately in another PR just after this is done. Little step by little step 🐌

**Comment by peterdesmet** [comment]
Oh, I forgot I logged it as an issue. 😄

**Review by peterdesmet — APPROVED** [review]
Updated description of `read_camtrap_dp()` function.

**Pull request merged**
