### PR TITLE
Add function to round coordinates

### PR DESCRIPTION
**Pull request by peterdesmet**
See #147 for implementation details.

### CODE REVIEW

**Review by damianooldoni — APPROVED** [review]
Nice work @peterdesmet. I have just added an example.

**Comment by damianooldoni** [comment]
One thing I forgot to add just now in my review. Maybe it would be better to write a note saying that we assume the deployments are a certain latitude (~ 🇧🇪 ?) when converting precision of latitude in meters.
Still, the best way would be to use the latitude in the deployment data and use a function to convert it to meters.

**Comment by peterdesmet** [comment]
We assume the latitudes are at the equator, which gives the largest possible uncertainty (see https://docs.gbif.org/georeferencing-best-practices/1.0/en/#table-uncertainty). I guess I could take latitude into account when calculating, but it makes it more complex. Maybe this could be done as an enhancement?

**Comment by damianooldoni** [comment]
Could you add your sentence (reported here below) in function documentation?
> We assume the latitudes are at the equator, which gives the largest possible uncertainty (see https://docs.gbif.org/georeferencing-best-practices/1.0/en/#table-uncertainty).

Thanks.

**Pull request merged**
