### PR TITLE
268 add news.md

### LINKED ISSUE #268: Add news.md
we have to start a news.md for v1.0. Use frictionless's news as inspiration.

### PR DESCRIPTION
**Pull request by PietrH**
Fixes #268

Using the [`NEWS.md` from frictionless](https://github.com/frictionlessdata/frictionless-r/blob/main/NEWS.md) as inspiration, I've added a NEWS.md with items from #244 and #207. I used `usethis::use_news_md()`.

I suggest we update `NEWS.md` iteratively as we bring more changes to the v1.0 branch.

### CODE REVIEW

**Review by peterdesmet — CHANGES_REQUESTED** [review]
- It seems that the current bullet points are already implemented and should be listed under a `camtraptor 0.20.0` header?
- The newly planned things for 1.0 should (for now) be listed under `camtraptor (development version)`

**Comment by PietrH** [comment]
Well spotted Peter. Changes in #207 are already implemented, but changes in #244 were merged into the `v1.0` branch, not `main`. 

* Do you think planned changes should be added to a separate heading _camtraptor (development version)_, even if they are not implemented in any branch at all? 

I was planning to merge this into v1.0, but if merging into main instead, I agree things merged into v1.0 should indeed go under  _camtraptor (development version)_

* Should we add this `NEWS.md` as part of `v1.0` or earlier?

**Comment by damianooldoni** [comment]
Hi. Well, not really. The only bullet point linked to something already developed, i.e. in `main` (v0.20), is 
> `write_dwc()` is now faster (#192)".
This issue seems solved by https://github.com/inbo/camtraptor/pull/207

**Comment by damianooldoni** [comment]
Decided with @PietrH to not mention v0.20 or earlier versions in `NEWS.md`.

**Review by damianooldoni — APPROVED** [review]
🔝

**Review by peterdesmet — APPROVED** [review]

**Comment by PietrH** [comment]
Leaflet is dependent on R3.6, so we need to up our minimum R requirement to R3.6

**Comment by damianooldoni** [comment]
Nice move ♟️ 
In this way we have a minimal check at 3.6.0 using Windows, probably the OS of the vast majority of users.

I think we are ready to merge this and move on? Once on v1.0, please pull the updated v1.0 in branch [259-datapkg-argument](https://github.com/inbo/camtraptor/tree/259-datapkg-argument) . In any case, I start the review of #271.

**Pull request merged**
