### PR TITLE
Create `deployments()`, `observations()` & `media()` to retrieve data

### PR DESCRIPTION
**Pull request by PietrH**
#232 
Peter: 
>Suggested in camtraptor July 2023 coding sprint
>
>Rationale: provide convenience functions to retrieve the tables/data frames from a camtrap dp object, so users don't have to retrieve them from package$data$tablename. Benefits:
>
>    Easier to understand than package$data$tablename
    Retrieving data is an important functionality, so should be tested
    Can be used by other functions that need to access the data
    Allows to change data model without affecting functionality
    Is in line with other suggested functions to retrieve data, such as taxonomy(), locations(), events()

### CODE REVIEW

**Comment by PietrH** [comment]
After discussion we've decided that `check_package()` should return `TRUE` for a valid camtrap-dp, or throw errors otherwise. Instead of the current behaviour where it'll return a `package` object

**Comment by PietrH** [comment]
Blocked by #247

**Review by damianooldoni — APPROVED** [review]
Well done! Thanks.
I have just added two more `expect_()` checks in tests and I also used this new functions everywhere in the package as they are not only better for users, but they are handy for us as well. 
Shorter lines, and easier to read/understand.

**Comment by damianooldoni** [comment]
I also allowed GitHub Actions tests to be triggered when we create PRs to the `v1.0` branch.

**Pull request merged**
