### PR TITLE
Replace `package`/`mica` with `x` in functions/documentaion

### PR DESCRIPTION
**Pull request by damianooldoni**
~**IMPORTANT**: blocked. DO NOT REVIEW/MERGE until PR #322 is merged and closed. @PietrH: I will also wait your upcoming PR about #324 if it's almost ready.~

This PR:

- Replaces argument `package` with `x` in function documentation, tests and vignette. `package` was used to be the first argument of many function. Now we call it `x` as in `camtrapdp`. See #323 and #324.
- Removes `mica` dataset (`/data/mica.rda`) and the camtrap data packages (raw data files in `inst/extdata/`). 
- updates `NEWS.md`
- updates documentation via `devtools::document()`

### CODE REVIEW

**Comment by PietrH** [comment]
I wouldn't wait for #324, I don't think I'll be submitting a PR today

**Comment by PietrH** [comment]
Consider converting to a draft PR

**Comment by damianooldoni** [comment]
Checked with @PietrH. He didn't have time to work on #324 before holidays. I will handle #324 in this PR as well.

**Review by sannegovaert — APPROVED** [review]
Nice!

**Pull request merged**
