### PR TITLE
Add  camera_functioning #177

### PR DESCRIPTION
**Pull request by Rafnuss**

### CODE REVIEW

**Review by peterdesmet — DISMISSED** [review]
The current paste0 will create comments with trailing or leading pipes, such as `<eventdescription> | ` or `| <camerafunctioning>`. @Rafnuss can you make this conditional, so that a pipe is only used when the two are present? I think this can be achieved by:

```R
comments <- c(.data$event_description, .data$camera_functioning) # Won't create elements for NULL values
paste(comments, collapse = " | ")
```

**Comment by damianooldoni** [comment]
@peterdesmet, @Rafnuss: is this PR ready to be merged? If yes, please let me know. I will pull from `main` after finalizing the other PR (#186) to avoid bad surprises.

**Comment by peterdesmet** [comment]
Yes, this can now be merged.

**Comment by damianooldoni** [comment]
Thanks @peterdesmet to take care about this! After merging #186 I will take care of this PR.

**Review by damianooldoni — APPROVED** [review]

**Pull request merged**
